# Generated by Django 2.0.4 on 2018-09-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_mates',
            field=models.ManyToManyField(blank=True, null=True, related_name='person_projects', to='projects.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, null=True, related_name='tech_used_in_projects', to='projects.Technology'),
        ),
    ]
