# Generated by Django 2.0.4 on 2018-09-25 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180924_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_mates',
            field=models.ManyToManyField(blank=True, related_name='person_projects', to='projects.Person'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='tech_used_in_projects', to='projects.Technology'),
        ),
    ]
