# Generated by Django 2.0.4 on 2018-09-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20180904_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_mates',
            field=models.ManyToManyField(to='team.TeamMate'),
        ),
    ]
