# Generated by Django 2.0.4 on 2018-09-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20180906_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='team_mates',
            field=models.ManyToManyField(related_name='person_projects', to='team.TeamMate'),
        ),
    ]
