# Generated by Django 2.0.4 on 2018-09-06 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20180906_0706'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team_mates',
        ),
    ]
