# Generated by Django 2.0.4 on 2018-09-06 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_skill_description'),
        ('projects', '0005_remove_project_team_mates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.TeamMate')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='team_mates',
            field=models.ManyToManyField(related_name='person_projects', to='projects.Person'),
        ),
    ]
