# Generated by Django 2.0.4 on 2018-09-01 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0002_auto_20180901_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publications',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
