# Generated by Django 2.0.4 on 2018-09-04 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Navigation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('full_url', models.CharField(blank=True, max_length=500, null=True)),
                ('for_footer', models.BooleanField(default=False)),
            ],
        ),
    ]
