# Generated by Django 2.0.4 on 2018-09-05 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='navigation',
            old_name='url',
            new_name='url_field',
        ),
    ]
