# Generated by Django 2.0.4 on 2018-09-04 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceplan',
            name='plan_features',
        ),
        migrations.AddField(
            model_name='planfeature',
            name='price_plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='plan_features', to='pricing.PricePlan'),
            preserve_default=False,
        ),
    ]
