# Generated by Django 2.0.4 on 2018-09-25 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planfeature',
            name='price_plan',
        ),
        migrations.AddField(
            model_name='planfeature',
            name='price_plan',
            field=models.ManyToManyField(related_name='plan_features', to='pricing.PricePlan'),
        ),
    ]
