# Generated by Django 2.0.4 on 2018-09-12 12:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_auto_20180904_0640'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priceplan',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='priceplan',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 12, 12, 55, 44, 994204, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
