# Generated by Django 2.0.4 on 2018-09-02 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=1000)),
                ('skill_level', models.IntegerField(blank=True, null=True)),
                ('skill_is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('social_url', models.URLField()),
                ('icon', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('picture_small', models.ImageField(upload_to='team/small/')),
                ('picture_big', models.ImageField(upload_to='team/big/')),
                ('job_title', models.CharField(max_length=1000)),
                ('contact_location', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('skills', models.ManyToManyField(to='team.Skill')),
                ('social_media', models.ManyToManyField(to='team.SocialMediaItems')),
            ],
        ),
        migrations.AddField(
            model_name='socialmediaitems',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_medias_links', to='team.TeamMate'),
        ),
        migrations.AddField(
            model_name='skill',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_skills', to='team.TeamMate'),
        ),
    ]
