# Generated by Django 2.0.4 on 2018-09-23 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=1000)),
                ('skill_level', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('skill_is_special', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('social_url', models.URLField()),
                ('icon', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TeamIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('picture_small', models.ImageField(upload_to='team/small/')),
                ('picture_big', models.ImageField(upload_to='team/big/')),
                ('job_title', models.CharField(max_length=1000)),
                ('contact_location', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='socialmediaitems',
            name='team_mate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_social_medias', to='team.TeamMate'),
        ),
        migrations.AddField(
            model_name='skill',
            name='team_mate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_skills', to='team.TeamMate'),
        ),
    ]
