# Generated by Django 2.0.4 on 2018-09-04 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20180904_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammate',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='teammate',
            name='social_media',
        ),
        migrations.AddField(
            model_name='skill',
            name='team_mate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_skills', to='team.TeamMate'),
        ),
        migrations.AddField(
            model_name='socialmediaitems',
            name='team_mate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_medias_links', to='team.TeamMate'),
        ),
    ]
