# Generated by Django 2.0.4 on 2018-09-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactInfo',
            new_name='ContactIntro',
        ),
    ]
