# Generated by Django 2.0.4 on 2018-09-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20180907_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='contacts/'),
        ),
    ]
