# Generated by Django 2.0.4 on 2018-09-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_contact_which_price_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='which_price_plan',
            field=models.CharField(choices=[('هیچکدام', 'هیچکدام'), ('پلن متغیر', 'پلن متغیر'), ('پلن ۹', 'پلن ۹'), ('پلن ۸', 'پلن ۸'), ('پلن ۷', 'پلن ۷'), ('پلن ۶', 'پلن ۶'), ('پلن ۵', 'پلن ۵'), ('پلن ۴', 'پلن ۴'), ('پلن ۳', 'پلن ۳'), ('پلن ۲', 'پلن ۲'), ('پلن ۱', 'پلن ۱')], default='هیچکدام', max_length=500),
        ),
    ]
