# Generated by Django 2.0.4 on 2018-09-12 10:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_auto_20180912_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='contact',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 9, 12, 10, 0, 13, 268910, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
