# Generated by Django 2.0.4 on 2018-09-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
